### ISSUE TITLE
Don't print 'null' to stdout for no-match

### ISSUE THREAD

**Issue by stephen-dexda** [mikefarah/yq#235]
For example, printing null to stdout breaks the following:

```bash
my_val="$(echo 'foo: bar' | yq -re '.someotherkey' || echo 'default_val')"
```

Since this will result in `null default_val`.

Instead, yq should output an error message to stderr on no match, at least in the case of `-e`.

**Comment by mikefarah** [comment]
Dupe of https://github.com/mikefarah/yq/issues/223

Happy to reopen 223 and discuss if you want

**Comment by stephen-dexda** [comment]
A bit different from that one:

* This is re. stdout vs. stderr on no match, not the exit code itself (although that's needed).
* That one is for exit 1 on null (which is wrong IMO), wherease this is for in conjunction with exit 1 on no match only.

We can reuse that bug instead though if you want :)

Reasonable behaviour I think would be:

* Match, but value is null: exit 0, print "null" to stdout (formatted per `-r` setting).
* No match, `-e` switch used: exit 1, don't print anything to stdout, print "no match" or similar to stderr.

**Comment by mikefarah** [comment]
yeah that makes sense to me

**Comment by stephen-dexda** [comment]
This was actually meant for kislyuk/yq but I didn't realise there were two different projects 😄 sorry. Hence the switches that don't apply to your version. But if it's an applicable bug, I can leave it open.

**Comment by nemchik** [comment]
I've just today come across a use case for this. I can agree with everything that's been said so far.

`null` is a value that could be intentionally assigned to something in the yml and should returned in that scenario, but not when nothing is found.

Example:
```yaml
services:
  watchtower:
    labels:
    container_name: watchtower
```
- `yq r watchtower.yml 'services.watchtower.container_name'` should return `watchtower` (it does currently)
- `yq r watchtower.yml 'services.NOTwatchtower.container_name'` should return nothing to stdout and return `no match` or similar to stderr and exit with a non-zero code (currently this returns `null` and exits with 0 as the exit code)

I've come up with a workaround for now but this is NOT how things should be handled:
`yq r watchtower.yml 'services.NOTwatchtower.container_name' | grep -v '^null$'` accomplishes not outputting null (but would be bad in a scenario where something is intentionally `null`)

**Comment by sklevenz** [comment]
I am supporting this use case and suggest to introduce a new flag. For example "-f". If set then yq quits with non zero return value in case of a key does not match.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1

**Comment by felix-hoc** [comment]
I think the non-zero exit code is not yet implemented, is that correct? It would be very useful to check if the value was read successfully. `jq` has the `-e` / `--exit-status` flag, which does exactly this. It would be great to have that for yq as well :)

**Comment by mikefarah** [comment]
oh yeah - I

**Comment by MalKeshar** [comment]
Hmm. I still have this behaviour on the latest release. What did I miss?

```
$ echo 'foo: bar' | yq e '.someotherkey' - 
null
$ yq -V
yq (https://github.com/mikefarah/yq/) version 4.16.2
```
